# Project information
site_name: OpenT8
site_description: 'Documentation for OpenT8'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://openpotato.github.io/opent8/'

# Copyright
copyright: 
  '&copy; 2025 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/imprint.php">Impressum</a> : <a href="https://legal.stueber.de/privacy.php">Datenschutz</a>'

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/openpotato/opent8'

# Theming
theme: 
  name: material
  language: de
  features:
    - navigation.footer
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: 'blue'
      accent: 'blue'
      toggle:
        icon: material/brightness-7
        name: In den Dunkelmodus wechseln
    - scheme: slate
      primary: 'blue'
      accent: 'blue'
      toggle:
        icon: material/brightness-4
        name: In den Hellmodus wechseln
  font: false
  favicon: 'assets/logos/favicon.ico'
  logo: 'assets/logos/logo.svg'
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

# Customization
extra_css:
  - assets/css/custom.css
    
# Social media
extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/openpotato.org
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@openpotato

# Plugins
plugins:
    - search
    - minify:
        minify_html: true

# Extensions    
markdown_extensions:
  - toc:
      permalink: true
  - def_list
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      

# Navigation  
nav:
  - Einführung: index.md
  - Spezifikation: specification.md
  - Bibliotheken: libraries.md
  - Community: community.md
  - Änderungslog: change-log.md
